Repository CSCI-GA-2820-SP23-003/promotions, pull requests merged in 2023-03, with the labels that each got.

#30 service/models.py: replace all instances of name with title
  service/models.py
Labels: bug

#31 init factory for db instantiation
  tests/factories.py
Labels: technical debt

#34 added get all promos operation and tests
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#41 removed id from deserialization
  service/models.py
Labels: bug

#46 linting fixes
  service/models.py
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: technical debt
